sudo: false

language: php

php:
  - 5.6
  - 7.0

script: phpunit --coverage-text

install:
  # gearman
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.0.3
  ## Composer
  - composer install

before_script:
  - gearmand -d

