language: php

php:
  - 5.6
  - 7.0

script: phpunit --coverage-text

services:
  - postgresql

before_install:
  - composer self-update
  - composer validate

install:
  # gearman
  - pecl install gearman
  ## Composer
  - composer install

before_script:
  - gearmand -d