language: php

php:
  - 5.6
  - 7.0

script: phpunit --coverage-text

before_install:
  - composer self-update
  - composer validate

install:
  # gearman
  - sudo apt-get install -y gearman-job-server
  - pecl install gearman
  ## Composer
  - composer install

before_script:
  - gearmand -d