language: php

php:
  - 5.6
  - 7.0

script: phpunit --coverage-text

before_install:
  - composer self-update
  - composer validate

install:
  # gearman
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.0.3
  ## Composer
  - composer install

before_script:
  - gearmand -d
